name: 버그 리포트
description: B1ND-AUTH-TEMPLATE에서 발생한 문제를 보고합니다. KOR-VER
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        📝 **기능 요청**은 [아이디어](https://github.com/Team-B1ND/B1ND-AUTH-TEMPLATE/discussions/categories/ideas) 섹션에 새 토론을 열어주세요.  
        
        📚 **문서 개선 요청**도 [아이디어](https://github.com/Team-B1ND/B1ND-AUTH-TEMPLATE/discussions/categories/ideas) 섹션에 올려주세요.  
        
        ❗ 새 이슈를 열기 전에 [기존 이슈](https://github.com/Team-B1ND/B1ND-AUTH-TEMPLATE/issues)를 검색하고, 관련 이슈에 👍로 투표해 주세요. 이를 통해 문제를 더 빠르게 해결할 수 있습니다.  
        
        🆘 프로젝트에 대한 도움이 필요하다면 ["Help"](https://github.com/Team-B1ND/B1ND-AUTH-TEMPLATE/discussions/categories/help) 섹션에 새 토론을 시작해 주세요.

  - type: input
    attributes:
      label: 재현 코드 링크
      description: |
        문제를 명확하게 재현할 수 있는 최소한의 코드를 제공해 주세요.  
        
        **유효한 재현 링크를 제공하지 않으면 이슈가 종료될 수 있습니다.**
      placeholder: 'https://github.com/user/my-minimal-b1nd-issue-reproduction'
    validations:
      required: false

  - type: textarea
    attributes:
      label: 재현 단계
      description: |
        문제를 재현하는 방법을 자세히 설명해 주세요.  
        
        코드 블록을 사용할 경우, [문법 강조](https://docs.github.com/ko/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting)가 올바른지 확인하세요.  
      placeholder: |
        1. 프로젝트를 시작합니다.
        2. X 버튼을 클릭합니다.
        3. Y 동작이 발생합니다.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 실제 동작과 기대한 동작
      description: |
        기대한 동작과 실제 발생한 동작을 명확하게 설명해 주세요.  
        
        가능한 경우 스크린샷, 로그, 기타 관련 정보를 포함해 주세요.  
        
        **정보가 불충분하면 이슈가 종료될 수 있습니다.**
      placeholder: |
        위 단계를 따르면 A가 발생할 것으로 예상했으나, 대신 B가 발생했습니다.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: 영향을 받은 영역 (해당하는 모든 항목 선택)
      multiple: true
      options:
        - '잘 모르겠음'
        - '인증 (Authentication)'
        - '연결 (Connection)'
        - 'UI 로딩 및 스트리밍'
        - '마크다운 (MDX)'
        - 'React 기능'
        - '테스트 환경'
        - '빌드 (Turbopack)'
        - 'TypeScript'
        - 'Webpack'
        - '문서화'
    validations:
      required: true

  - type: textarea
    attributes:
      label: 추가 정보
      description: |
        문제를 이해하는 데 도움이 될 수 있는 추가 정보를 제공해 주세요.  
        
        예시:  
        - 어떤 환경에서 배포하고 있나요? (Docker, AWS 등)  
        - 특정 브라우저나 플랫폼에서만 발생하나요?  
      placeholder: |
        특정 브라우저에서만 문제가 발생하며, 로컬 환경에서는 재현되지 않습니다.
