name: 'Report a documentation issue'
description: Report an issue with the B1ND-AUTH-TEMPLATE documentation ENG-VER.
title: 'Docs: '
type: Docs
body:
  - type: markdown
    attributes:
      value: |
        📚 **Before opening a new documentation issue**, please check if this is something you can help us with!  
        
        Your contributions are welcomed and appreciated. See our [Docs Contribution Guide](https://github.com/Team-B1ND/B1ND-AUTH-TEMPLATE/blob/main/CONTRIBUTING.md) to learn how to edit the B1ND-AUTH-TEMPLATE documentation.  
        
        📢 **If you are requesting new documentation**, please open a post in our [discussions](https://github.com/Team-B1ND/B1ND-AUTH-TEMPLATE/discussions/new?category=ideas) section instead.  

        💖 Thank you for helping us improve our documentation!

  - type: textarea
    attributes:
      label: What is the documentation issue?
      description: |
        Describe the issue in the documentation.  
        For example: "There is incorrect or outdated information in the `contributing.md` file."
      placeholder: |
        Example: The installation steps are outdated in the README.md file.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Is there any context that might help us understand?
      description: |
        Provide any additional context or details that might help us understand the issue better.  
        For example: "This section is confusing because it lacks examples."
      placeholder: |
        Example: This section needs more examples for better understanding.
    validations:
      required: false

  - type: input
    attributes:
      label: Does the docs page already exist? Please link to it.
      description: |
        If the documentation page already exists, please provide a link to it.  
        For example: "https://github.com/Team-B1ND/B1ND-AUTH-TEMPLATE/blob/main/docs/contributing.md"
      placeholder: 'https://github.com/Team-B1ND/B1ND-AUTH-TEMPLATE/blob/main/docs/contributing.md'
    validations:
      required: false
