name: '문서 이슈 보고'
description: B1ND-AUTH-TEMPLATE 문서에 대한 문제를 보고합니다. KOR-VER.
title: 'Docs: '
type: Docs
body:
  - type: markdown
    attributes:
      value: |
        📚 **새로운 문서 이슈를 열기 전에**, 이 문제가 여러분이 해결할 수 있는 것인지 확인해 주세요!  
        
        여러분의 기여는 언제나 환영하고 감사합니다. B1ND-AUTH-TEMPLATE 문서를 편집하는 방법은 [문서 기여 가이드](https://github.com/Team-B1ND/B1ND-AUTH-TEMPLATE/blob/main/CONTRIBUTING.md)에서 확인할 수 있습니다.  
        
        📢 **새로운 문서 요청**이 있을 경우, [토론](https://github.com/Team-B1ND/B1ND-AUTH-TEMPLATE/discussions/new?category=ideas) 섹션에 게시물을 작성해 주세요.  

        💖 문서 개선에 도움을 주셔서 감사합니다!

  - type: textarea
    attributes:
      label: 문서 이슈가 무엇인가요?
      description: |
        문서에서 발생한 문제를 설명해 주세요.  
        예시: "contributing.md 파일에 잘못되었거나 오래된 정보가 있습니다."
      placeholder: |
        예시: README.md 파일의 설치 단계가 오래되었습니다.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 문제를 이해하는 데 도움이 될 추가적인 정보가 있나요?
      description: |
        문제를 더 잘 이해하는 데 도움이 될 수 있는 추가적인 설명이나 정보를 제공해 주세요.  
        예시: "이 섹션은 예시가 부족해서 이해하기 어렵습니다."
      placeholder: |
        예시: 이 섹션은 더 나은 이해를 위해 예시가 추가되어야 합니다.
    validations:
      required: false

  - type: input
    attributes:
      label: 문서 페이지가 이미 존재하나요? 링크를 제공해 주세요.
      description: |
        문서 페이지가 이미 존재한다면 해당 페이지의 링크를 제공해 주세요.  
        예시: "https://github.com/Team-B1ND/B1ND-AUTH-TEMPLATE/blob/main/docs/contributing.md"
      placeholder: 'https://github.com/Team-B1ND/B1ND-AUTH-TEMPLATE/blob/main/docs/contributing.md'
    validations:
      required: false
