name: Label Issue

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  label-set-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Add label based on issue template
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.issue.number;
            const issue_body = context.payload.issue.body.toLowerCase();
            
            
            let labels = [];
            if (issue_body.includes('bug report')) {
              labels.push('bug');
            } else if (issue_body.includes('documentation')) {
              labels.push('docs');
            }

            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                labels: labels
              });
            }
