name: Label Issue

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  label-set-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Add 'stale' label to new issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.issue.number;

            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              labels: ['stale']
            });
